### ISSUE TITLE
fedora-modular.repo dnf config file should point to f27 repo

### ISSUE THREAD

**Issue by sctweedie** [fedora-modularity/hp#18]
Currently, /etc/yum.repos.d/fedora-modular.repo from fedora-modular-repos.rpm refers to 

baseurl=https://kojipkgs.fedoraproject.org/compose/latest-Fedora-Modular-rawhide/compose/Server/$basearch/os

It should point at the latest-Fedora-Modular-27 compose instead.

**Comment by sgallagher** [comment]
@sctweedie 
Just to be sure, we are talking about https://kojipkgs.fedoraproject.org/compose/latest-Fedora-Modular-27/compose/Server/ correct?

**Comment by sctweedie** [comment]
Yes; from contyk

"the configuration for both is identical and they're created at the same time; at some point they will begin to differ, so I would definitely start using things with 27 in the name if they exist"

**Comment by sgallagher** [comment]
https://pagure.io/fedora-modular-repos/pull-request/1

**Comment by contyk** [comment]
The configuration now ships with metalinks pointing to `Modular-Bikeshed-Server`. This doesn't change anything regarding this issue, it's just an update :)

I expect us to address this sometime next week. Currently looking into how to make maintaining two sets of nearly identical package lists, tags and dist-git repositories as painless as possible.

**Comment by sgallagher** [comment]
This was merged a month ago.

**Comment by contyk** [comment]
Was it? I think the f27 branch/version points to bikeshed.

**Comment by sgallagher** [comment]
@contyk Well, the PR listed in this ticket was merged. If it needs to be changed again, that's a different story.

**Comment by contyk** [comment]
Yes, that one was.

Basically we need Bikeshed metalinks in the `master` branch (pulled into `platform:master`) and F27 metalinks for nightlies, Beta, GA, updates and updates-testing in the `f27` branch (pulled into `platform:f27`). The modules already pull the right content but `fedora-modular-repos-27` points to Bikeshed and doesn't include any of the other repo config files at the moment.

Do you think we should track this in a new issue?

**Comment by sgallagher** [comment]
No, we can use this ticket.

**Comment by contyk** [comment]
This should be fixed in the latest F27 composes.
