### ISSUE TITLE
missing cmake-filesystem package

### ISSUE THREAD

**Issue by ppisar** [fedora-modularity/hp#21]
The platform module is missing cmake-filesystem binary package (from cmake component). We decided we will keep cmake-filesystem in platform, the rest will be in cmake module.

I built cmake-bootstrap module and then when building cmake module, I got this root.log error:

```
DEBUG util.py:439:    - nothing provides cmake-filesystem(x86-64) needed by cmake-3.9.3-1.module_7c9e41dd.x86_64
```

This is because platform module does not deliver cmake-filesystem package. Please add it. 

See cmake-bootstrap build macros for disabling unneeded feature, especially:

```
%_with_bootstrap 1
```

for building it without already having cmake in the build root.

**Comment by sgallagher** [comment]
Fixed in the latest platform builds
