### ISSUE TITLE
drop xmlrpc-c

### ISSUE THREAD

**Issue by igor-raits** [fedora-modularity/hp#23]
upstream maintains 3 streams in parallel and I would like to have xmlrpc-c module with 3 streams while now it is locked by platform.

I tried to remove from toplevel-binary-packages.txt and it went away in runtime.

**Comment by sgallagher** [comment]
This was added and then temporarily reverted because it broke installer. I will make this change again once the xmlrpc-c module is ready.

**Comment by contyk** [comment]
Since we're now pursuing the hybrid approach with a non-modular compose, this report no longer applies. Closing.
