### ISSUE TITLE
platform:f27 is missing python3-rpm-generators package

### ISSUE THREAD

**Issue by ppisar** [fedora-modularity/hp#32]
python3-devel binary package run-requires python3-rpm-generators, but the package is not in the plaform:f27. This bug prevents from building Python 3 packages against platform:f27 and pytothon3:3.6. See <https://koji.fedoraproject.org/koji/taskinfo?taskID=23095957>.

 Please add python3-rpm-generators package into the platform:f27 module.

**Comment by ppisar** [comment]
This is still issue in latest platform-f27-20171114200751 <https://koji.fedoraproject.org/koji/taskinfo?taskID=23155623>. The modulemd is missing python-rpm-generators component.

**Comment by ppisar** [comment]
This blocks building nodejs-6, nodejs-8, meson-master, cmake-bootstrap-3.9 and cmake-3.9.

**Comment by igor-raits** [comment]
@ppisar nice thing is that python3-devel was not supposed to be there :)

**Comment by ppisar** [comment]
As far as I know in python3 for platform:f27 is supposed to be almost empty
and all the packages should be provided by platform:f27. This is the differnece
between f27 and master. Ask torsava for more details.

**Comment by ppisar** [comment]
Great. But that's not all. Now we need this change in the dist-git and build the module.

**Comment by sgallagher** [comment]
@ignatenkobrain What is the set of new deps needed in the F27 platform? Note that we can't use BPL for this directly anymore, since we're manually curating the F27 modulemd now. However, if you can get me the diff for master, I can probably work it up for F27.
