### ISSUE TITLE
drop vim

### ISSUE THREAD

**Issue by nphilipp** [fedora-modularity/hp#33]
Currently, vim(-minimal) is in platform because sudo used to have a hard dependency on it. From sudo's dist-git commit 3e6b39b18504cd49db16af4725d5799ab177ab23 on it only recommends vim-minimal, so dropping the dependency on it is possible.

**Comment by sgallagher** [comment]
Note: this change is currently only in the master (Rawhide) branch of sudo. We need to keep this in mind in platform:f27

**Comment by contyk** [comment]
Since we're now pursuing the hybrid approach with a non-modular compose, this report no longer applies. Closing.
