### ISSUE TITLE
Other packages to place

### ISSUE THREAD

**Issue by dpal** [fedora-modularity/hp#4]
certmonger, gssproxy, clevis, tang, luks, luksmeta, kerberos, etc.
There are tons of other packages than need to be reviewed for example the python stack. Does it belong to platform?

**Comment by contyk** [comment]
This is a rather diverse list. Some of these might make more sense than others. Some might be more suitable for separate modules.

Regarding the Python stack, Platform will bundle a separate, somewhat limited implementation, disconnected from full Python stacks shipped in application level modules. This is mainly to support our system management tooling such as dnf. In general, library bindings shouldn't build against this implementation and we'll have to look into repackaging components that build all the bindings in one package. Unfortunately this won't be trivial. See https://fedoraproject.org/wiki/Changes/Platform_Python_Stack for a little more info on the planned bundled stack.

**Comment by contyk** [comment]
Since we're now pursuing the hybrid approach with a non-modular compose, this report no longer applies. Closing.
