### ISSUE TITLE
glib2

### ISSUE THREAD

**Issue by igor-raits** [fedora-modularity/hp#5]
I think it makes sense to include such core library (also because upsteam is very careful about keeping ABI stable, didn't remember about API stability, probably they keep it as deprecated for multiple releases and then remove it)

**Comment by Conan-Kudo** [comment]
We also basically need this for DNF and other things...

**Comment by igor-raits** [comment]
having it as dependency and explicitly specified is different ;)

**Comment by contyk** [comment]
Obviously `glib2` is pulled in as a dependency of quite a few packages. I'm not against listing is as an explicit content as it is something most people would expect to be available and supported.
