### ISSUE TITLE
btrfs-progs

### ISSUE THREAD

**Issue by igor-raits** [fedora-modularity/hp#6]
Would be useful to have btrfs-progs in Platform, since it is prerequisite for btrfs (which is installed on my laptop).

**Comment by Conan-Kudo** [comment]
If we're doing this thing with the modularity stuff, it'd be nice if my systems weren't all broken because btrfs was left out somehow...

**Comment by contyk** [comment]
There's no reason to drop support for `btrfs-progs`. Adding it to the explicit Platform list.
