### ISSUE TITLE
gnupg2 / gpgme / other-related-stack

### ISSUE THREAD

**Issue by igor-raits** [fedora-modularity/hp#7]
I think it makes sense to have all that gpg2 stuff in platform explicitly because this is what rpm/dnf/microdnf uses and basically it is core stuff.

**Comment by contyk** [comment]
`gnupg2` is part of the Platform. I'm not sure we need to list anything else explicitly. If you have a different opinion, can you explain why?

**Comment by igor-raits** [comment]
@contyk gpgme is the only one library which has reasonable API to use gnupg functionality from C (though it has bindings for python, c++ and something else)

**Comment by contyk** [comment]
Ok, gpgme is in.
