### ISSUE TITLE
At least one crypto library (openssl?)

### ISSUE THREAD

**Issue by igor-raits** [fedora-modularity/hp#8]
I think we should have at least one crypto library explicitly defined as API in Platform (unstable crypto libraries is worst thing when you are dealing with any crypto).

**Comment by Conan-Kudo** [comment]
When it comes to ABI guarantees, GnuTLS and NSS are probably the better ones. I personally prefer GnuTLS, but I know that there's been some kind of effort to use OpenSSL more.

I'd suggest GnuTLS and OpenSSL, as those two are popular and very well done libraries.

**Comment by contyk** [comment]
I think all of these make sense to be part of the Platform, otherwise we're asking packagers to bundle their own copies, which would be a really bad idea in this case.

**Comment by Conan-Kudo** [comment]
Indeed.

**Comment by contyk** [comment]
Added all these, plus nettle. Thanks.
